export {buyCake} from './cake/cakeActions'
export {buyVanIC} from './iceCream/iceCreamActions'
export {buyChocIC} from './iceCream/iceCreamActions'
export {buyStrawIC} from './iceCream/iceCreamActions'
export {orderIC} from './iceCream/iceCreamActions'